export const projects = [
  {
    title: 'Amazon Clone',
    description: "Using React, Node.js, Express & Firebase. This is a Full Stack Application  built deployed with firebase. Where you can Sign-up, Log-in, add items to basket, pay and checkout. Payement gateway intigrated with Stripe API",
    image: 'images/amazon.png',
    tags: ['Firebase', 'Express', 'React', 'Node'],
    source: 'https://google.com',
    visit: 'https://github.com/GourabSanyal/amazon-clone-react',
    id: 0,
  },
  {
    title: 'Birthday Reminder',
    description:"A dummy data is fetched and rendered at the front end, where each array of data contains an id, name, age, image. I have used a simple funcionality with useState hook to render the raw data in a form of list. As you clear the data and refresh the page, you will show those fetched data again.",
    image: '/images/1.png',
    tags: ['React', 'JavaScript'],
    source: 'https://stoic-curran-7f33cb.netlify.app',
    visit: 'https://github.com/GourabSanyal/birthday-reminder-react',
    id: 1,
  },
  {
    title: 'Menu',
    description: "A dataset with different food items, each of them containing six parameters are being fetched, destruchered and set to different components. As you click on 'All' you can see eveery food item which are avaialable, also other options such as 'Breakfast', 'Lunch', 'Shakes'  are there to differentiate varities of food according to the time of the day and their types",
    image: '/images/3.png',
    tags: ['React', 'JavaScript'],
    source: 'https://jolly-nightingale-cb3d85.netlify.app',
    visit: 'https://github.com/GourabSanyal/menu-react',
    id: 2,
  },
  {
    title: 'cart',
    description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
    image: '/images/cart.png',
    tags: ['React', 'JavaScript'],
    source: 'https://github.com/GourabSanyal/chat-app-react',
    visit: 'https://gracious-kepler-7650ba.netlify.app/',
    id: 4,
  },
  {
    title: 'Colour Picker',
    description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
    image: '/images/5.png',
    tags: ['React', 'JavaScript'],
    source: 'https://friendly-varahamihira-319bc9.netlify.app/',
    visit: 'https://github.com/GourabSanyal/colour-generator-react',
    id: 5,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'Started my journey', },
  { year: 2018, text: 'Worked as a freelance developer', },
  { year: 2019, text: 'Founded JavaScript Mastery', },
  { year: 2020, text: 'Shared my projects with the world', },
  { year: 2021, text: 'Started my own platform', },
];